server:
  port: ${PORT:443}

  ssl:
    enabled: true
    # keystore format
    key-store-type: PKCS12
    # keystore location
    key-store: classpath:keystore/server.p12
    # keystore password
    key-store-password: ENC(wiMOCNAAHFLBhhpIgvQQ/g/Ox7vw9oitELOx7bJCPOgmGrZac9lAWJ7QGPrp7CyL)

    # SSL protocol to use
    protocol: TLS
    # Enabled SSL protocol

    enabled-protocols: TLSv1.2
    #client-auth: need
    #trust store location
    #trust-store: classpath:keystore/server-truststore.p12
    #trust store password
    #trust-store-password: changeit
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
    min-response-size: 10240

spring:
  config:
    import: application-data.yml
  flyway:
    baseline-on-migrate: true
  # for swagger-ui
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
  security:
    jwt:
      jwtSecret: ENC(3DNdSzuVKsOicKHSLgyXFVDP7rD0CVSAS2kzm1rYiMKFEhf/z5RmDHRkT9jwk3Rp)
      jwtExpirationMs: 8640000
  jpa:
    show-sql: false

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:123}
# nac configure
nac:
  session-ttl: 3000000
# ids configure
netflow:
  # Свойства, связанные с анализатором пакетов
  analyze:
    routerType: KEENETIC
    analyzeFrequencyMillis: 5000
    updateMeanValueTimeMillis: 6000000
    maxUniqueDestinationPortCount: 40
    flowMultiplierLimitation: 5
    # Свойства, связанные с сборщиком пакетом

  router:
    ipAddress: 192.168.1.1
    username: admin
    password: ENC(6bdk1Xm4ha9jye1A7Jp1AFv+Oq3Snl98Isontn4n7pN+Mqam1UWc9s9KoCxdiwzN)
    accessListName: netflow
    collector:
      port: 2055